[project]
name = "deep-research-agent"
version = "0.1.0"
description = "Deep Research Assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ag-ui-langgraph>=0.0.25",
    "copilotkit>=0.1.78",
    "deepagents>=0.4.3",
    "dotenv>=0.9.9",
    "fastapi>=0.115.14",
    "langchain>=1.2.10",
    "langchain-openai>=1.1.10",
    "python-dotenv>=1.2.1",
    "tavily-python>=0.7.21",
    "uvicorn[standard]>=0.41.0",
]
